### ISSUE TITLE
generate_quality_facets fails with disk error

### ISSUE THREAD

**Issue by kulizhsy** [openfoodfacts/robotoff#346]
The daily job to compute quality facets has been failing, stack trace:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 3129, in execute_sql
    cursor.execute(sql, params or ())
psycopg2.errors.DiskFull: could not resize shared memory segment "/PostgreSQL.887373656" to 50438144 bytes: No space left on device


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/opt/robotoff/robotoff/scheduler/latent.py", line 27, in generate_quality_facets
    generate_fiber_quality_facet()
  File "/opt/robotoff/robotoff/scheduler/latent.py", line 41, in generate_fiber_quality_facet
    ProductInsight.source_image.is_null(False),
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 1975, in iterator
    return iter(self.execute(database).iterator())
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 1898, in inner
    return method(self, database, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 1969, in execute
    return self._execute(database)
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 2141, in _execute
    cursor = database.execute(self)
  File "/usr/local/lib/python3.7/site-packages/playhouse/postgres_ext.py", line 490, in execute
    cursor = self.execute_sql(sql, params, commit=commit)
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 3136, in execute_sql
    self.commit()
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 2902, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 3129, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: could not resize shared memory segment "/PostgreSQL.887373656" to 50438144 bytes: No space left on device
```

According to [this](https://stackoverflow.com/questions/56751565/pq-could-not-resize-shared-memory-segment-no-space-left-on-device) post, increasing the shared memory size via docker flag should do the trick.

**Comment by kulizhsy** [comment]
Increased shared memory to 1gb in docker-compose.yml

Will monitor if it mitigated the issue - the next run is scheduled for tomorrow.

**Comment by kulizhsy** [comment]
Increasing the shared memory size has resolved this issue.
