### ISSUE TITLE
Robotoff should raise if updates on off are failing

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/robotoff#562]
**Describe the bug**

After switching to new Robotoff production, product updates request from robotoff where not allowed on openfoodfacts because we forgot to change ip address allow list. (`ip_whitelist_session_cookie` in `Config2.pm`).
Yet we did not get Sentry entries for that !

**Expected behavior**
We should have gotten Sentry entries with an exception.

robotoff.off.update_product should have raised on error, see why it didn't raise

**Comment by raphael0202** [comment]
What kind of error did we have?
We handle edit errors during Product Opener updates here: https://github.com/openfoodfacts/robotoff/blob/dc787553dfa463a003d45a16c6bf882a9b9b8d07/robotoff/insights/annotate.py#L136

**Comment by raphael0202** [comment]
I just tested HTTP 401 with a mock server, and an error is raised:

```
2023-05-19 05:24:43,824 :: MainProcess :: MainThread :: INFO :: New annotation received from unknown annotator (annotation: 1, insight: 00000ed5-4aa3-4eb7-b1d3-5efc3850b4c6)
[2023-05-19 05:24:45 +0000] [26] [ERROR] Socket error processing request.
Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 194, in handle_request
    util.reraise(*sys.exc_info())
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/gunicorn/util.py", line 626, in reraise
    raise value
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/falcon/api.py", line 269, in __call__
    responder(req, resp, **params)
  File "/opt/robotoff/robotoff/app/api.py", line 318, in on_post
    annotation_result = save_annotation(
  File "/opt/robotoff/robotoff/app/core.py", line 455, in save_annotation
    result = annotate(
  File "/opt/robotoff/robotoff/insights/annotate.py", line 703, in annotate
    return ANNOTATOR_MAPPING[insight.type].annotate(
  File "/opt/robotoff/robotoff/insights/annotate.py", line 136, in annotate
    raise e
  File "/opt/robotoff/robotoff/insights/annotate.py", line 126, in annotate
    return cls._annotate(insight, annotation, update, data, auth, is_vote)
  File "/opt/robotoff/robotoff/insights/annotate.py", line 167, in _annotate
    annotation_result = cls.process_annotation(
  File "/opt/robotoff/robotoff/insights/annotate.py", line 343, in process_annotation
    add_category(
  File "/opt/robotoff/robotoff/off.py", line 229, in add_category
    update_product(params, server_type=product_id.server_type, auth=auth, **kwargs)
  File "/opt/robotoff/robotoff/off.py", line 460, in update_product
    r.raise_for_status()
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://httpstat.us/401
```

I guess we didn't spot it on Sentry. I'm closing this issue.
